version: '3'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "9292:9292"
    links:
      - postgres
    privileged: true
    environment:
      DATABASE_URL: "${DOCKER_DATABASE_URL}"
      POSTGRES_USER: "${DOCKER_POSTGRES_USER}"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: tgifs
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "${DOCKER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"
      POSTGRES_DB: tgifs