development:
  adapter: postgresql
  database: tgif_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1

test:
  adapter: postgresql
  database: tgif_test
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1

production:
  database: tgif
  url: <%= ENV['DATABASE_URL'] %>